### ISSUE TITLE
Add GridSearchCV for identifying best model

### ISSUE THREAD

**Issue by NisargPipaliya** [Rakesh9100/ML-Project-Drug-Review-Dataset#1]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

As being a gssoc contributor i would like to contribute to this repo, by adding GridSearchCV to the code base that would help us to identify the best model among the available models

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by s0oraj** [comment]
Hi @NisargPipaliya . 
I am an open source contributer at gssoc.

Would you like to assign this issue to me? My Resume: [Resume.pdf](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/files/11521326/Resume.pdf)

Here is my background in ML:
1) 6 months plus experience in working under college professors for research project on medical image classification.
2)Got 228 global rank in Amazon ML Challenge 2023 out of 30000+ teams participating.
3) Experienced with trainig machine Learning Models. Including image preprocessing techniues such as histrogram equilization, augmentation, stationary wavelet transformation, image segmentation. Along with feature extraction from models like resnet50 inceptionv3 vgg16 etc

Looking forward to hear from you.

**Comment by VardaPanchal005** [comment]
I would like to work on this issue. Please assign me

**Comment by ASHWIN492** [comment]
Hey @NisargPipaliya  , I am a GSSOC contributor . I would like to work on this issue.

**Comment by NisargPipaliya** [comment]
@s0oraj @ArunMaramraj 
@ASHWIN492 @VardaPanchal005 
Guys, I am too a GSSOC'23 contributor and i created this issue so that the owner/maintainer of this repo can assign me this.

**Comment by VardaPanchal005** [comment]
> @s0oraj @ArunMaramraj @ASHWIN492 @VardaPanchal005 Guys, I am too a GSSOC'23 contributor and i created this issue so that the owner/maintainer of this repo can assign me this.

My bad , I'm new to open source organization and I'm trying to understand the rules and regulations.

**Comment by ASHWIN492** [comment]
> @s0oraj @ArunMaramraj @ASHWIN492 @VardaPanchal005 Guys, I am too a GSSOC'23 contributor and i created this issue so that the owner/maintainer of this repo can assign me this.

sorry i am new to this so don't know

**Comment by Vethan123** [comment]
hii there. I want to work on this issue . please assign it to me

**Comment by UditSharma9999** [comment]
I'm a contributor for GSSoC '23, I want to work on this issue. Please assign me.

**Comment by Sadhana-Panthi** [comment]
I'm a contributor for GSSoC '23. Please, assign me an issue.

**Comment by NisargPipaliya** [comment]
@ASHWIN492 
@VardaPanchal005 
No problem guys.
you can connect with me @  [LinkedIN](https://www.linkedin.com/in/nisarg-pipaliya-12b078172/)

@UditSharma9999 @Vethan123 
@sadhana70 

Guys Read the previous message.

**Comment by NisargPipaliya** [comment]
@Rakesh9100
I am a GSSOC'23 contributor and created this issue,
Can you please assign me the Issue?

**Comment by Rakesh9100** [comment]
https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/issues/19 @NisargPipaliya and every contributors

**Comment by Rakesh9100** [comment]
<https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/issues/19> @NisargPipaliya and every contributors

Hope you will understand.

**Comment by NisargPipaliya** [comment]
oK bro....

**Comment by Rakesh9100** [comment]
@NisargPipaliya Assigning you, Go ahead

**Comment by NisargPipaliya** [comment]
Yeah...Let's get started
The Code is too buggy

**Comment by Rakesh9100** [comment]
@NisargPipaliya Pls provide the status of your work

**Comment by NisargPipaliya** [comment]
@Rakesh9100 
I am having some problems in running the code in my notebook.

it has many bugs, so working on it.

**Comment by Rakesh9100** [comment]
Pull the latest changes @NisargPipaliya You have time till 31st may EOD

**Comment by Rakesh9100** [comment]
@s0oraj Do you want to work?

**Comment by ayan-joshi** [comment]
Prerequisites
 I am an Open Source Contributor
 I checked to make sure that this issue has not already been filed
Description
As being a gssoc contributor, as explained in the issue I will add GridSearchCV to the code base that would help us to identify the best model among the available models

Screenshots
No response

Code of Conduct
 I follow [Contributing Guidelines](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
 
 @Rakesh9100 please assign me this issue

**Comment by Rakesh9100** [comment]
@ayan-joshi Start working

**Comment by Rakesh9100** [comment]
@ayan-joshi Status of your PR

**Comment by ayan-joshi** [comment]
I am trying to add the gridsearch I have written code for it but when I am adding it in the file the code is collapsing or having some issue

**Comment by Rakesh9100** [comment]
Should I unassign @ayan-joshi

**Comment by ayan-joshi** [comment]
Give me one chance till tommorow

**Comment by Rakesh9100** [comment]
Okay

**Comment by Abhinavcode13** [comment]
Assign this to me @Rakesh9100

**Comment by Rakesh9100** [comment]
Assigned @Abhinavcode13

**Comment by karthikbhandary2** [comment]
Hey @Rakesh9100 I would like to work on this.

**Comment by Rakesh9100** [comment]
@karthikbhandary2 Do you want to be assigned?

**Comment by karthikbhandary2** [comment]
yes @Rakesh9100

**Comment by Rakesh9100** [comment]
Assigned @karthikbhandary2 proceed

**Comment by karthikbhandary2** [comment]
@Rakesh9100 for which model should I apply gridsearch?

**Comment by Rakesh9100** [comment]
Apply for as many implemented models you can to identify the best among them @karthikbhandary2

**Comment by karthikbhandary2** [comment]
ok @Rakesh9100

**Comment by Rakesh9100** [comment]
Update of your work pls @karthikbhandary2

**Comment by karthikbhandary2** [comment]
I need some time @Rakesh9100 . It is taking 6 to 8 hrs for a model to run on using grid search. I need some time.

**Comment by Rakesh9100** [comment]
Yes, I know it will definitely take time for running the model but I need an update time to time whether contributor is working or not @karthikbhandary2

**Comment by karthikbhandary2** [comment]
ok. So till now I ran linear regression with grid search and it gave the same results as the one without. Now I'm running it with randomforest.

**Comment by karthikbhandary2** [comment]
Hey @Rakesh9100 I have run the grid search on random forest. I would like to know whether to keep the code or remove it by taking a look at these results.

![grid randforest plot 1](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/assets/34509856/7a178770-bc49-4dce-8961-7f2d25164143)
![grid randforest plot 2](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/assets/34509856/67520175-d9d0-4c73-9730-e44436a0ebcf)
![grid randforest plot 3](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/assets/34509856/7e5a6331-22ee-4e68-b0a6-bc296f1bfe8f)
![grid randforest plot 4](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/assets/34509856/2c6315a9-112f-494a-9a27-b3de24dbf2d2)

**Comment by Rakesh9100** [comment]
You can keep the codes of the one which comes best with GridSearchCV @karthikbhandary2

**Comment by karthikbhandary2** [comment]
ok @Rakesh9100
