### ISSUE TITLE
Implement EDA and to apply advanced ML algorithms

### ISSUE THREAD

**Issue by devanshidevanshidevanshi** [Rakesh9100/ML-Project-Drug-Review-Dataset#100]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

The ideation is :
1) To apply advanced ML algorithms like XGBoost, AdaBoost, CatBoost, etc
2) To perform a detailed EDA and preprocessing
3) To integrate the project with a website using Flask, HTML, and CSS to showcase accurate results, visually appealing graphs, and plots.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Pls don't create duplicate issues again and again. You have already opened issue number 99 for the same.
