### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by smty2018** [Rakesh9100/ML-Project-Drug-Review-Dataset#101]
### Description

Want to add a CodeofConduct.md file to ensure a safe environment for everyone to work.

**Comment by smty2018** [comment]
@Rakesh9100 please assign me this issue

**Comment by Rakesh9100** [comment]
This is already present. <https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/CODE_OF_CONDUCT.md> Pls create new issues.
