### ISSUE TITLE
Add codeql workflow for code scanning

### ISSUE THREAD

**Issue by harmeetsingh11** [Rakesh9100/ML-Project-Drug-Review-Dataset#103]
### What feature?

As your project's tech stack includes Python. The repository does not have workflow for code scanning.
I want to add the codeql workflow to automate security checks. CodeQL is the code analysis engine developed by GitHub to identify vulnerabilities in code. It will analyze your code and display the results as code scanning alerts. It will be enabled on every push, commit and pull request using GitHub actions.

### Record
- [x] I agree to follow this project's Code of Conduct
- [x] I'm a GSSoC'23 contributor
- [x] I want to work on this issue

Thanks

**Comment by Rakesh9100** [comment]
As this is an innovative but a small project, so I don't think we need this. Pls work on other issues.
