### ISSUE TITLE
Add dependabot.yml file

### ISSUE THREAD

**Issue by Anshika-Jain02** [Rakesh9100/ML-Project-Drug-Review-Dataset#106]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

*We need to add dependabot.yml file as it helps us to keep our dependencies up to date. Every day, it checks your dependency files for outdated requirements and opens individual PRs for any it finds.*

@Rakesh9100 please assign me this issue under gssoc'23.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
PR Update @Anshika-Jain02

**Comment by Rakesh9100** [comment]
PR Update pls @Anshika-Jain02

**Comment by Anshika-Jain02** [comment]
Sir, i will create the PR by today itself. @Rakesh9100
