### ISSUE TITLE
Integrate the project with a website using Flask, HTML, and CSS

### ISSUE THREAD

**Issue by devanshidevanshidevanshi** [Rakesh9100/ML-Project-Drug-Review-Dataset#107]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

The ideation is to integrate the project and turn it into a full fledged website using Flask, HTML and CSS in order to showcase results and display grpahs for better understanding

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Assigning @devanshidevanshidevanshi Proceed

**Comment by Rakesh9100** [comment]
Update of your work pls @devanshidevanshidevanshi
