### ISSUE TITLE
Improve accuracy using ensemble learning

### ISSUE THREAD

**Issue by Shubhamkumar-op** [Rakesh9100/ML-Project-Drug-Review-Dataset#108]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I will  use ensemble learning technique for boosting the model accuracy on training and test data also using seaborn and matplotlib for better vizualisation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Update of your work @Shubhamkumar-op

**Comment by sahaycodes** [comment]
@Rakesh9100, I would like to work on this issue under GSSOC'23 
Will update you about the progress made in every 3-4 days. 
Therefore, kindly assign me this issue.

**Comment by sahaycodes** [comment]
@Rakesh9100, I have added some more Data Visualization and currently working on Ensemble Learning Technique, the issue should be completed by 14th July. Will keep you posted.

**Comment by Rakesh9100** [comment]
Okay go ahead @sahaycodes

**Comment by sahaycodes** [comment]
@Rakesh9100, due to some commitments ...the issue should be resolved by 16th July

**Comment by Rakesh9100** [comment]
Update of your PR pls @sahaycodes

**Comment by sahaycodes** [comment]
@Rakesh9100  will need 2-3 more days, kind of busy with some work, Sorry for the delay.

**Comment by Rakesh9100** [comment]
Any status @sahaycodes

**Comment by sahaycodes** [comment]
Will create a PR by 4/8/23. Sorry for the delay @Rakesh9100
