### ISSUE TITLE
Add Embedding layers with LSTM, GRU and Convo1D

### ISSUE THREAD

**Issue by Soumya1219** [Rakesh9100/ML-Project-Drug-Review-Dataset#109]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I want to add Embedding layers with LSTM, GRU and if possible with Conv1D also. 
I am an open source contributor and previously worked with deep learning algorithms and had a good knowledge on it. We can create these layers using keras and I want to implement and learn more. 

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Update of your work pls @Soumya1219

**Comment by Soumya1219** [comment]
I will make pull request by tomorrow morning.. 
Kindly give me some time till then :)

**Comment by Rakesh9100** [comment]
Okay @Soumya1219

**Comment by Mohsinkkk** [comment]
//assign me
