### ISSUE TITLE
Add Scatter matrix for testing data

### ISSUE THREAD

**Issue by dhruvsaxena11** [Rakesh9100/ML-Project-Drug-Review-Dataset#119]
### Description

@Rakesh9100 
Respected Sir,
I will add the scatter matrix for the testing data with scatter plots and histogram for the features of the testing dataset.

Please kindly assign this issue to me.

Thank You

Dhruv Saxena

**Comment by Rakesh9100** [comment]
No need of more plots now. Every required plots and matrix are already added for every models. Pls work on other good issues @dhruvsaxena11
