### ISSUE TITLE
Perform EDA and Implement Deep Learning models

### ISSUE THREAD

**Issue by 1912-khushi** [Rakesh9100/ML-Project-Drug-Review-Dataset#12]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

As we know Deep learning , based models have surpassed classical machine learning based approaches in various text classification tasks, including sentiment analysis, news categorization, question answering, and natural language inference.
1. Perform complete EDA to get insights 
2. Use Sampling Techniques
3. We can implement few deep learning models in order to increase the efficiency of the project to get better outcomes.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by varsha089** [comment]
Please assign this issue to me under GSsoC 2023.

**Comment by tushtithakur** [comment]
Hi, I would like to contribute. Please assign the task to me under GSSOC'23.

**Comment by Rakesh9100** [comment]
@1912-khushi Assigning you, go ahead

**Comment by Mubashir-Ul-Hassan** [comment]
Hi, @Rakesh9100  I would like to contribute. Please assign the task to me under GSSOC'23.

**Comment by Rakesh9100** [comment]
@1912-khushi Pls provide the update of your work

**Comment by 1912-khushi** [comment]
> @1912-khushi Pls provide the update of your work

By when should i provide the updated work?

**Comment by Rakesh9100** [comment]
Do provide me the status of what have you done, working or not on this issue and when will you create PR? @1912-khushi
