### ISSUE TITLE
Implement PyCaret Regression for Model Comparison

### ISSUE THREAD

**Issue by manishkumar00208** [Rakesh9100/ML-Project-Drug-Review-Dataset#120]
### Description

PyCaret is an open-source, low-code machine learning library in Python that automates machine learning workflows. It is an end-to-end machine learning and model management tool that speeds up the experiment cycle exponentially and makes you more productive.
The PyCaret’s regression module has over 25 algorithms and 10 plots to analyze the performance of models. Be it hyper-parameter tuning, ensembling, or advanced techniques like stacking, PyCaret’s regression module has it all.

I've tried this on many ML projects and it works awsome! As this makes the life easier by comparing the different machine learning algorithms by their accuracy, MAE, MSE, etc., then selecting one and finally plotting and implementing that.

### Screenshots

Here's the sample screenshot of usage of the models comparison:
![Models_compare](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/assets/76589863/b25a4a29-500e-4c9c-94bf-12fca085577f)

### Additional information

For the given dataset(training & testing), I can work it on PyCaret and give you the best results and code (contribution) by assigning me with this issue.

**Comment by manishkumar00208** [comment]
@Rakesh9100 Please Assign me with this issue!

**Comment by Rakesh9100** [comment]
Issue number 2 is already opened for the same. Pls comment there and I will assign you @manishkumar00208

**Comment by manishkumar00208** [comment]
@Rakesh9100 I'm Ok with that! Please assign me for that issue then...!! #2
