### ISSUE TITLE
Add Sentiment Analysis using Deep Learning

### ISSUE THREAD

**Issue by Garvit414** [Rakesh9100/ML-Project-Drug-Review-Dataset#121]
### Description

I want to add the feature of Sentiment Analysis using Deep Learning with better accuracy. I will try to build a better neural network that tries to do sentiment analysis.
Please assign it to me.

**Comment by Rakesh9100** [comment]
Status of your work @Garvit414

**Comment by Garvit414** [comment]
My exams are going on, so it gets delayed, but I will do it ASAP.
Please understand @Rakesh9100 
Sorry for the delay.

**Comment by Rakesh9100** [comment]
Okay @Garvit414
