### ISSUE TITLE
Add Logging module for storing the logs

### ISSUE THREAD

**Issue by umangtank** [Rakesh9100/ML-Project-Drug-Review-Dataset#124]
### Description

for any working projects logs are the very important feature.
logs play important role to identify the error and helps debugging, So i want to add logs in this project.

**Comment by Rakesh9100** [comment]
What do you mean by storing logs in this project? Pls explain in detail about the approach @umangtank

**Comment by umangtank** [comment]
"Storing logs in the project means implementing a logging mechanism that captures relevant information during the execution of the code and saves it in log files. This helps in identifying errors, debugging the project, and gaining insights into its behavior.

To achieve this, I plan to integrate a suitable logging framework, such as Python's logging module, into the project. The framework will allow us to add log statements at strategic points within the code, capturing important events, error messages, timestamps, and other relevant data.

**Comment by abhisheks008** [comment]
Sounds pretty cool to me, this will also help us to debug. Also the contributors will be helpful in this. "Yes" from my side.

@Rakesh9100 what do you think?

**Comment by Rakesh9100** [comment]
Yes seems good for the project, Assigning @umangtank

**Comment by umangtank** [comment]
Ok thank you

**Comment by Rakesh9100** [comment]
@umangtank Update of your work pls

**Comment by umangtank** [comment]
yes, i am working on it, make a pull request soon

**Comment by abhyudaya29** [comment]
please assign this to me
thank you

**Comment by Rakesh9100** [comment]
@umangtank PR status
