### ISSUE TITLE
Usage of sentimental Analysis on Drug Review

### ISSUE THREAD

**Issue by nehavish006** [Rakesh9100/ML-Project-Drug-Review-Dataset#13]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Utilization of  NLP techniques to process Drug review dataset to calculate Sentiment rating for some new inclusions.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Aditi323** [comment]
Please assign this to me as a GSSOC contributor.

**Comment by mesieeeee** [comment]
Good Evening 

Currently i am working on NLP techniques only specifically, where in sentiment analysis i have performed for dataset reviews of amazon, and flipkart, and keen intrested to get my hands on this amazing dataset of drugs.
please assign it to me so i can explore and work on it.
Thanks

**Comment by UditSharma9999** [comment]
I'm a contributor for GSSoC '23, I want to work on this issue. Please assign me.

**Comment by Rakesh9100** [comment]
@nehavish006 Assigning you, proceed

**Comment by Rakesh9100** [comment]
@nehavish006 Update of your work

**Comment by nehavish006** [comment]
> @nehavish006 Update of your work

Done with the preprocessing

**Comment by Rakesh9100** [comment]
@nehavish006 You are unassigned as enough time provided
@Aditi323 @mesieeeee Do you want to work?

**Comment by nehavish006** [comment]
Give me 1 more day...i am going to finish

**Comment by Rakesh9100** [comment]
Okay till 3rd June EOD @nehavish006

**Comment by nehavish006** [comment]
> Okay till 3rd June EOD @nehavish006

Okay!!thanks a lot
