### ISSUE TITLE
Add bar graph and line graphs

### ISSUE THREAD

**Issue by nandini601** [Rakesh9100/ML-Project-Drug-Review-Dataset#130]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Using matplotlib, creating a bar graph and line graph.
Contributor of girlscript summer of code.
Please give this issue to me for resolving.

### Screenshots

<img width="316" alt="4N1Nt" src="https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/assets/98204182/ae505c11-b53c-44e7-9860-e5dbdaa610d8">

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Almost every graphs are already created for each model. Pls work on new issues @nandini601
