### ISSUE TITLE
Add Sarima model

### ISSUE THREAD

**Issue by ayushrathore111** [Rakesh9100/ML-Project-Drug-Review-Dataset#131]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I want to add new  model in our dataset named as sarima which is for seasonal analysis and forecasting

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by ayushrathore111** [comment]
@Rakesh9100 please assign this to me
thank you

**Comment by Rakesh9100** [comment]
Update of your work pls @ayushrathore111

**Comment by ayushrathore111** [comment]
@Rakesh9100 some errors are coming. I would fix it asap

**Comment by Rakesh9100** [comment]
@ayushrathore111 Pls provide the status

**Comment by ayushrathore111** [comment]
trying to fixing the errors. I will provide status today evening

**Comment by Rakesh9100** [comment]
Any status @ayushrathore111
