### ISSUE TITLE
Add Contribution.md file

### ISSUE THREAD

**Issue by PurviSaini** [Rakesh9100/ML-Project-Drug-Review-Dataset#132]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I look for the contributing guidelines in this repository but it's kind of hidden, we usually expect it to be in the main folder along with the readme.md file.
The method to contribute is written in the readme.md file and some important pointers in the contribution.md file, so why not compile them both into a single file namely contribution.md as separating the contribution guidelines into a dedicated contribution.md file helps keep the project's documentation organized. It allows for a clear distinction between the information in the readme.md file and the guidelines intended for contributors.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
It's already present. Check here [Contributing Guidelines.md](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/CONTRIBUTING_GUIDELINES.md). Pls go through the codebase and repository properly and avoid creating duplicate issues @PurviSaini

**Comment by PurviSaini** [comment]
The contribution guidelines as mentioned by you and the method to contribute (specified in readme), I just wanted to compile them into one. The issue was not to create a new contribution.md, it was to put all the content of contribution into that file. But I think as mentioned by you it's alright to keep contribution guidelines and method to contribute in separate files. 
Didn't mean to create a duplicate issue, apologies for that.
Learnt from this.
Thankyou!!
