### ISSUE TITLE
Update results screenshots in Readme file

### ISSUE THREAD

**Issue by Juhibhojani** [Rakesh9100/ML-Project-Drug-Review-Dataset#135]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I would like to update readme file with the latest screenshots of results.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Juhibhojani** [comment]
Hii, the requirements.txt file doesn't include catboost as well as optuna. Would you like me to update that as well? Also, do I include all the graphs for each algorithm or just scatter plots for train and test data as well as metrics works?

**Comment by Rakesh9100** [comment]
Yes, you can do update the libraries file and also include `pycaret`.

You have to include every graphs, plots, and matrix present in the code for each model @Juhibhojani

**Comment by Rakesh9100** [comment]
Yes, you can do update the libraries file and also include `pycaret`.

Yes, you can run the code and have to include every graphs, plots, and matrix being displayed after running the code those are missing in the readme file for each model in the proper format @Juhibhojani

**Comment by Juhibhojani** [comment]
I am unable to run SVM algorithm, every time I try, My laptop ends up being stuck, so i won't be able to upload screenshots for SVM. Also due to my ongoing exams, this might take longer but I will try to complete this ASAP

**Comment by Rakesh9100** [comment]
Okay, you can skip for SVM and upload the screenshots of every other models @Juhibhojani
