### ISSUE TITLE
Add black linter workflow

### ISSUE THREAD

**Issue by metabiswadeep** [Rakesh9100/ML-Project-Drug-Review-Dataset#14]
Add a suitable linter to ensure proper linting of the code. As a project with multiple users contributing to it, it is essential to maintain a proper linting style to ensure better code readability by users. An excellent way to do this is by automatic linting checks using GitHub actions.

I would like to work on this project as a part of GSSoC 23. Please assign this issue to me.

**Comment by Rakesh9100** [comment]
There are many linting checks available. Pls specify in detail what all checks you will implement as there are many beginners in open source too who should not face any problem from this checks. @metabiswadeep

**Comment by metabiswadeep** [comment]
Initially I am thinking about implementing black linting.

**Comment by Rakesh9100** [comment]
Okay proceed @metabiswadeep

**Comment by Rakesh9100** [comment]
@metabiswadeep Provide the status of your work

**Comment by metabiswadeep** [comment]
Working on integrating the black linter with the repo.
