### ISSUE TITLE
Implement proper visualizations to understand the dataset better

### ISSUE THREAD

**Issue by Nabanita29** [Rakesh9100/ML-Project-Drug-Review-Dataset#145]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

There are no proper visualization for a beginner to understand the dataset they will be working on for preprocessing the data.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Nabanita29** [comment]
I can work on this sir!

**Comment by Rakesh9100** [comment]
There is no need for this visualisation. You are assigned with issue number 80 so pls work on that @Nabanita29
