### ISSUE TITLE
Add models

### ISSUE THREAD

**Issue by Enhancer18** [Rakesh9100/ML-Project-Drug-Review-Dataset#149]
To write a Python code that preprocesses the Drug Review Dataset from UCI, extracting date information, handling missing values, and converting text data to numerical representations using TF-IDF. Categorical columns are encoded, and memory usage is optimized. Four ML models (Random Forest, SVM, Logistic Regression, Naive Bayes) are trained and evaluated for accuracy, and their performance is visualized using cross-validation plots to find the best model for drug review analysis.

**Comment by Rakesh9100** [comment]
Python code is already written @Enhancer18
