### ISSUE TITLE
Add seaborn.categorical and seaborn.matrix for better visualization

### ISSUE THREAD

**Issue by Abhinavcode13** [Rakesh9100/ML-Project-Drug-Review-Dataset#15]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Implementation approach to resolve this issue.

seaborn.categorical: This submodule provides functions for visualizing categorical data which makes the project look more better in terms of visualization.
If your drug review dataset contains categorical variables such as drug types, ratings, or side effects, you can use functions like barplot, countplot, or violinplot

seaborn.matrix: This submodule provides functions for visualizing matrices and rectangular datasets.
If your drug review dataset contains tabular data with multiple variables, you can use functions like heatmap to create a color-encoded grid that visualizes patterns or correlations between the variables.

### Screenshots

Just for example same thing will be implemented for different drugs.

seaborn.categorical :
![1_dXH4YyPEHbUNl6Nuz8eBHA](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/assets/126642111/960be98b-0276-4800-9fed-847a3272a8e9)

seaborn.matrix:
![OiPkj](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/assets/126642111/d22b2d00-7a6e-4869-86b7-f0b3ce6ece32)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Zedoman** [comment]
Please assign this issue to me. As i have knowledge in AIML field and also working in this field recently. Please assign this under GSSOC'23.

**Comment by Abhinavcode13** [comment]
Kindly assign this issue to me @Rakesh9100 !!

**Comment by Rakesh9100** [comment]
@Abhinavcode13 Assigning you, Start working

**Comment by Mubashir-Ul-Hassan** [comment]
Hi, @Rakesh9100 I would like to contribute. Please assign the task to me under GSSOC'23.

**Comment by Abhinavcode13** [comment]
@Mubashir-Ul-Hassan Im already working !!

**Comment by Rakesh9100** [comment]
@Abhinavcode13 Update of your work pls

**Comment by Abhinavcode13** [comment]
Hello @Rakesh9100 issue I'm not able to run my main py even if i installed all the dependencies.

**Comment by Rakesh9100** [comment]
Connect to project's channel on discord for queries.

**Comment by Rakesh9100** [comment]
@Zedoman Do you want to work

**Comment by Abhinavcode13** [comment]
instead of helping you closed the PR @Rakesh9100

**Comment by Rakesh9100** [comment]
Pls do check your PR. You are not providing any response neither here nor on project's discord channel. Atleast provide any update since many contributors are there who need chance to work. @Abhinavcode13
