### ISSUE TITLE
Add Code of conduct

### ISSUE THREAD

**Issue by mohit-dhote** [Rakesh9100/ML-Project-Drug-Review-Dataset#158]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

We propose adding a comprehensive Code of Conduct to our repository to ensure a safe, respectful, and inclusive environment for all contributors and users. This code will serve as a guideline for behavior, promoting diversity, reducing conflicts, and attracting a more comprehensive range of perspectives.

I want to work on this issue under GSSOC23, kindly assign this to me. @Rakesh9100

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Its already present. Do check here <https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/CODE_OF_CONDUCT.md>
Pls work on new issues.

**Comment by mohit-dhote** [comment]
okay I'll work on some another issue
