### ISSUE TITLE
Add other models and algos for better analysis of the dataset

### ISSUE THREAD

**Issue by AnuragJha003** [Rakesh9100/ML-Project-Drug-Review-Dataset#16]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Please assign me this issue I am very excited to work on it 

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by AnuragJha003** [comment]
@Rakesh9100  pls assign me this issue

**Comment by sijalalyy** [comment]
I am GSSOC 23 contributor assign this to me

**Comment by Rakesh9100** [comment]
@AnuragJha003 Assigning you, proceed and try
Many similar issues are also open so merging will depend whose accuracy and other factors will be good

**Comment by Mubashir-Ul-Hassan** [comment]
Hi, @Rakesh9100 I would like to contribute. Please assign the task to me under GSSOC'23.

**Comment by AnuragJha003** [comment]
@Mubashir-Ul-Hassan I have been already assigned this issue bro

**Comment by Mubashir-Ul-Hassan** [comment]
Bro I want to contribute and want to gain skill I don't want to waste my
summer so please guide me want I do.

**Comment by Rakesh9100** [comment]
@Mubashir-Ul-Hassan Head to discord server of GSSoC23 for these discussions and queries you have

**Comment by Mubashir-Ul-Hassan** [comment]
Ok thanks alot

**Comment by Rakesh9100** [comment]
@AnuragJha003 Provide the update of your work

**Comment by Rakesh9100** [comment]
@sijalalyy Do you want to work?

**Comment by sijalalyy** [comment]
> @sijalalyy Do you want to work?

Yes i want to work on this.

**Comment by Rakesh9100** [comment]
Which models and algos will you implement? Specify in detail @sijalalyy

**Comment by sijalalyy** [comment]
Algos and Models that can improve the analysis 
1. Vectorization Techniques:
   a. Bag-of-Words (BoW): This technique represents text data as a frequency count of words in each document.
   b. TF-IDF: Term Frequency-Inverse Document Frequency is a measure that reflects the importance of a word in a document corpus.
   c. Word2Vec: This technique represents words as vectors in a continuous vector space, capturing semantic relationships.

2. Classification Algorithms:
   a. LinearSVC: Linear Support Vector Classifier is a variant of the Support Vector Machine algorithm, known for its effectiveness in text classification tasks.

**Comment by AnuragJha003** [comment]
I m working using word2vec and tf idf and SVC and have also thought of
using Random forest with xgboost for it .... Sorry for the late reply net
was down in my region and very slow over the last 2/3 days due to a
maintenance  work

**Comment by AnuragJha003** [comment]
Pls reassign me my net was virtually dead for the last 2/3 days:(

**Comment by Rakesh9100** [comment]
@AnuragJha003 When will you create PR?

**Comment by AnuragJha003** [comment]
Within some days I was not able to work a bit because of my poor net
connection in the region. I started working on it and will create it very
soon .

**Comment by jahnvisahni31** [comment]
Hi, @Rakesh9100 I would like to contribute. Please assign the task to me under GSSOC'23.
