### ISSUE TITLE
Add Contributor page in the website

### ISSUE THREAD

**Issue by HimanshuNarware** [Rakesh9100/ML-Project-Drug-Review-Dataset#160]
### Description

Details
Is your feature request related to a problem? Please describe.
Our Contributors page in the website
Describe the solution you'd like
We can add a Contributors page in the website. which is shows the name and the profile image of the contributor.and the number of commits is done by the contributor

**Comment by Rakesh9100** [comment]
This is not needed for this project. Pls work on other good issues.
