### ISSUE TITLE
Add a Website Using Flask, HTML, and CSS

### ISSUE THREAD

**Issue by swetha3456** [Rakesh9100/ML-Project-Drug-Review-Dataset#17]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

As described in the README file, this project does not yet have a GUI. I would like to create a website for this using Flask, HTML, and CSS. 

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by swetha3456** [comment]
Hi @Rakesh9100, please assign this issue to me. I would like to work on it.

**Comment by ghost** [comment]
@Rakesh9100  hello sir i can do in less time please assign this task to me it will be my pleasure if i work on it

**Comment by sijalalyy** [comment]
I am GSSOC 23 contributor assign this to me i want to work on this

**Comment by StutiShah01** [comment]
I m willing to work on this issue

**Comment by Rakesh9100** [comment]
@swetha3456 similar issue No. 7 is already open so you can start your work, if yours will be good I will merge

**Comment by swetha3456** [comment]
@Rakesh9100 Sure, will do. Thank you!

**Comment by Rakesh9100** [comment]
@swetha3456 By when will you be able to do and create PR since its been 4 days you are assigned.

**Comment by swetha3456** [comment]
@Rakesh9100 I have been working on it and should be done in two days. Will create the PR by this Wednesday.

**Comment by jahnvisahni31** [comment]
Hi, @Rakesh9100 I would like to contribute. Please assign the task to me under GSSOC'23.

**Comment by Mimi97-aqua** [comment]
Hi @Rakesh9100 I would like to work on this. Please assign it to me

**Comment by Rakesh9100** [comment]
@swetha3456 You are unassigned, can't provide you more time

**Comment by sijalalyy** [comment]
I have experience in html, css, flask and i have made some websites as well, assign me this issue please. i want to work on this under gssoc'23

**Comment by Neilblaze** [comment]
@sijalalyy / @stuti187 you're in the queue. Do you want to take this up?

**Comment by sijalalyy** [comment]
Yes. I want to work on this. I do have experience in web development also.

**Comment by Neilblaze** [comment]
@sijalalyy Cool! I'm assigning you this! :)

**Comment by sijalalyy** [comment]
> @sijalalyy Cool! I'm assigning you this! :)

Thankyou

**Comment by Rakesh9100** [comment]
@sijalalyy Pls hold, another issue already exists to setup the GUI in streamlit. Work on other issues.
