### ISSUE TITLE
Enhance accuracy by using multiple regression models at a time

### ISSUE THREAD

**Issue by KEERTHI1912** [Rakesh9100/ML-Project-Drug-Review-Dataset#2]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Hey, am a fellow contributor of GSSOC'23 and would like to implement pycaret module to test and deploy about 25 regression models and select the best model with above 90% accuracy. AutoML is advanced machine learning technique and with appropriate tuning and ensembling, we would get much better insights on drug reviews by different patients.

### Screenshots

![image](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/assets/75976487/926da58d-8595-47a3-9a5d-96a89cb5ba75)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by ManaswiKasiraju** [comment]
I am a GSSOC contributor. I would like to work on this issue

**Comment by prousium** [comment]
Please assign me this issue so I can contribute to your project.

**Comment by Abhinavcode13** [comment]
kindly assign this issue to me @Rakesh9100 !!

**Comment by sijalalyy** [comment]
I am GSSOC 23 contributor assign this to me i want to work on this

**Comment by TheNobody-12** [comment]
Assign me this @KEERTHI1912

**Comment by Rakesh9100** [comment]
@KEERTHI1912 Assigning you, Proceed

**Comment by Rakesh9100** [comment]
@KEERTHI1912 Update of your work pls

**Comment by Rakesh9100** [comment]
@ManaswiKasiraju @prousium Do you want to work?

**Comment by holkarjuhi1712** [comment]
I am a contributer of gssoc'23 I would like to work on this project. 
Kindly, assign it to me

**Comment by Rakesh9100** [comment]
@holkarjuhi1712 Have you read the issue? What work will you do pls brief.

**Comment by ShreeparnaDhara** [comment]
Hi! I am Shreeparna Dhara and I am a contributor in gssoc 2023. I have worked on a machine learning project in my college which you can check in this link
 https://colab.research.google.com/drive/1XpY2nON3f7y2TAXyEj7FhbESdS8TdQ-2?usp=sharing

**Comment by holkarjuhi1712** [comment]
@Rakesh9100  I have worked on car owner classification model.which was based on machine learning. 
I have applied KNN, gaussian naive bayes, decision algorithms and finalized guassian naive bayes algorithm for the same. With accuracy, precision, recall >90%
So, I can apply multiple regression algorithm here and work on this model

**Comment by Rakesh9100** [comment]
Okay proceed @holkarjuhi1712

**Comment by holkarjuhi1712** [comment]
Can u pls provide me with dataset

**Comment by Rakesh9100** [comment]
Have you not went thorugh the repo and its codebase. Datasets are already present. @holkarjuhi1712

**Comment by holkarjuhi1712** [comment]
Okay thanks👍I will go forward

**Comment by Rakesh9100** [comment]
Update of your work pls @holkarjuhi1712

**Comment by holkarjuhi1712** [comment]
I will update you till tomorrow evening

**Comment by geyani998** [comment]
@Rakesh9100  Can you please assign me this issue?

**Comment by Rakesh9100** [comment]
Assigned you, proceed @manishkumar00208

**Comment by Rakesh9100** [comment]
@manishkumar00208 Do you want to be assigned?

**Comment by manishkumar00208** [comment]
Yes! I would love to....!! Thank you.

**Comment by manishkumar00208** [comment]
@Rakesh9100 please assign me to this issue as you closed my issue #120 because of the already existence of #2.
