### ISSUE TITLE
Fix some import issues

### ISSUE THREAD

**Issue by leidZhang** [Rakesh9100/ML-Project-Drug-Review-Dataset#211]
### Description

I used mypy to test the project, and I found some import errors. I have attached the test result of mypy
[mypy_result_MPDRD (2).txt](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/files/14900243/mypy_result_MPDRD.2.txt)

The following are the related errors: 
ML-Project-Drug-Review-Dataset\main.py:993: error: Name "GridSearchCV" is not defined  [name-defined]
ML-Project-Drug-Review-Dataset\main.py:1950: error: Name "hub" is not defined  [name-defined]
ML-Project-Drug-Review-Dataset\main.py:1954: error: Name "tf" is not defined  [name-defined]
ML-Project-Drug-Review-Dataset\main.py:1958: error: Name "tf" is not defined  [name-defined]
ML-Project-Drug-Review-Dataset\main.py:1960: error: Name "tf" is not defined  [name-defined]
ML-Project-Drug-Review-Dataset\main.py:1961: error: Name "tf" is not defined  [name-defined]
ML-Project-Drug-Review-Dataset\main.py:1962: error: Name "tf" is not defined  [name-defined]

**Comment by Nithinkumar3000** [comment]
Hi! 
Install tensorflow as - pip install tensorflow
Now, import tensorflow as - import tensorflow as tf

"tf not defined" issue can be cleared

**Comment by therohithborana** [comment]
Please assign this issue to me.

**Comment by ShreyaAwasekar** [comment]
install tensorflow as ! pip install tensorflow
import tensorflow as tf
from tensorflow import keras

**Comment by sonalisdas** [comment]
Hello, I'm a GSSoC'24 contributor and wish to work on this issue.

**Comment by K-Svayam05** [comment]
Hello! I am a GSSoC '24 Contributor, and being experienced with Python, Machine Learning, Regression models, Classification models and python libraries, I would like to work on this issue. So I request you to assign this task to me!
