### ISSUE TITLE
Implement Web Scraping Using Multiprocessing

### ISSUE THREAD

**Issue by Ashgen12** [Rakesh9100/ML-Project-Drug-Review-Dataset#22]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Hi
I'm Ashis Baidya | Contributor GSSOC'23.
Many libraries and models are available for web scraping of data related to drugs,[in our case patients reviews and drugs effect on them]. There I'm willing to implement python libraries which can increase the efficiency of the web scraping and reduce the amount of time to scrap a data using:- requests,Bs4, html5lib,dask,scrapy and multiprocessing .

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by SohamD242** [comment]
Hi,
I'm Soham Deshpande  (Contributor GSSOC'23)
Many websites doesn't offer API so to tackle this we can use Web Scraping to access data in easy and structured manner.
Python libraries like bs4, BeautifulSoup, Scrapy, Selenium etc. are generally used for web scraping.
Here I'm willing to apply these libraries and use an effective way of Multiprocessing to speed up Web Scrapping.
Multiprocessing is very helpful, when multiple URLs are scraped to get the data. It will perform scraping on multiple URLs thus saving our time.

**Comment by Rakesh9100** [comment]
@Ashgen12 Okay assigning you, proceed

**Comment by Rakesh9100** [comment]
@Ashgen12 Update of your work

**Comment by Ashgen12** [comment]
@Rakesh9100  yeah i had updated the work, i had pulled the code for updation of web scraping, here is the link :- 
https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/pull/62
