### ISSUE TITLE
Add Requirements.txt file

### ISSUE THREAD

**Issue by Grogu22** [Rakesh9100/ML-Project-Drug-Review-Dataset#23]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

To maintain a python project we need to create a requirements file to avoid dependency conflicts in the future..
I will create a virtual environment for this project and create a requirements.txt file which can be installed by :
```$ pip install -r requirements.txt```

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by StutiShah01** [comment]
please assign this task to me

**Comment by Grogu22** [comment]
> please assign this task to me

Dude 🙂

**Comment by Rakesh9100** [comment]
Pls specify what libraries you will add in that .txt file as not needed for this project @Grogu22

**Comment by stuti187** [comment]
> Pls specify what libraries you will add in that .txt file as not needed for this project @Grogu22

all the libraries that are used for performing EDA like numpy ,pandas and libraries which is used for importing models also

**Comment by Grogu22** [comment]
yup.. writing it once I manage to run the main.py successfully !! (with modifications)

**Comment by Rakesh9100** [comment]
Okay
