### ISSUE TITLE
Change Plot Confusion Matrix to ConfusionMatrixDisplay

### ISSUE THREAD

**Issue by Grogu22** [Rakesh9100/ML-Project-Drug-Review-Dataset#24]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

the method ```plot_confusion_matrix``` from ```sklearn.metrics``` has been _deprecated since scikit-learn version 1.0_.
Either use an older version of  sklearn and specify it in the requirements.txt file or use the method ```ConfusionMatrixDisplay``` from ```sklearn.metrics``` 
Documentation link : https://scikit-learn.org/stable/modules/generated/sklearn.metrics.ConfusionMatrixDisplay.html#sklearn-metrics-confusionmatrixdisplay

### Screenshots

<img width="430" alt="image" src="https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/assets/83173038/8ad72685-b95e-48f4-aa35-5de2ec2807cc">

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Okay proceed @Grogu22

**Comment by Grogu22** [comment]
Hey, @Rakesh9100 #36 also completes this issue

**Comment by Rakesh9100** [comment]
Yes, reviewed.
