### ISSUE TITLE
Fix some of the errors

### ISSUE THREAD

**Issue by ishrita08** [Rakesh9100/ML-Project-Drug-Review-Dataset#25]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Traceback (most recent call last):
  File "c:\Users\ISHRITA\AppData\Local\Temp\Temp2_ML-Project-Drug-Review-Dataset-main.zip\ML-Project-Drug-Review-Dataset-main\main.py", line 10, in <module>    
    from sklearn.metrics import mean_squared_error, r2_score, accuracy_score, confusion_matrix, plot_confusion_matrix
ImportError: cannot import name 'plot_confusion_matrix' from 'sklearn.metrics' (C:\Users\ISHRITA\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\__init__.py)

### Screenshots

![image](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/assets/111135297/aa91be3d-c5f3-4933-a2e8-4fbcb77f25b6)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by karthikbhandary2** [comment]
I think some one raised an issue for this

**Comment by Rakesh9100** [comment]
Issue is already opened before. Pls work on other @ishrita08
