### ISSUE TITLE
Add LSTM Model

### ISSUE THREAD

**Issue by Mochoye** [Rakesh9100/ML-Project-Drug-Review-Dataset#26]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Hey Everyone!

Myself Archisman | Contributor GSSOC'23

> Based on the dataset in the repo, I would recommend using a long short-term memory (LSTM) network.

Here are some specific suggestions for using an LSTM network for the project:

1. **Extract features from the text of the review:** The LSTM network can be used to extract features from the text of the review. These features can then be used to train a machine-learning model that can predict the sentiment of the review.

2. **Identify the sentiment of the review:** The LSTM network can be used to identify the sentiment of the review. This can be done by training the LSTM network on a dataset of reviews that have been labeled with the sentiment.

3. **Recommend drugs to users based on the sentiment of the review:** The LSTM network can be used to recommend drugs to users based on the sentiment of the review. This can be done by training the LSTM network on a dataset of reviews that have been labeled with both sentiment and the drug that was recommended to the user.

By following these suggestions, the LSTM network can be used to improve the accuracy and efficiency of the project.

### Code of Conduct

- [x] I follow [Contributing Guidelines](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Mochoye** [comment]
I would like to work on this issue under GSSOC'23. I would appreciate if the issue is assigned to me.

**Comment by Rakesh9100** [comment]
@Mochoye Assigning you, proceed

**Comment by dynamicdhxx** [comment]
I would like to work on this issue under GSSOC'23. Kindly assign the issue to me. @Rakesh9100

**Comment by Rakesh9100** [comment]
This issue is already completed @dynamicdhxx Work on other issues
