### ISSUE TITLE
Add readme badges

### ISSUE THREAD

**Issue by S-ishita** [Rakesh9100/ML-Project-Drug-Review-Dataset#28]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I want to add readme badges.Please assign this issue to me 

### Screenshots

![badges](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/assets/104543751/dc4a79c4-a08c-4a21-8e22-fec61d4beff4)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Assigning you @S-ishita
