### ISSUE TITLE
Fix some errors in main file

### ISSUE THREAD

**Issue by Shiv-Expert2503** [Rakesh9100/ML-Project-Drug-Review-Dataset#29]
### Prerequisites

- [X] I am an Open Source Contributor
- [x] I checked to make sure that this issue has not already been filed

## Error
The main.py has so many errors in it like a basic machine learning model can't predict float values but here y_train and y_test are float which is one of the major errors and the second one which I've seen so far is the problem when fitting the data in linear regression. The third error is in the library itself which is in line 7 plot_confusion_matrix is no more available. The fourth error is in the path or train and test dataset, the way in which they are assigned is not valid.

## Solution
I've fixed most of them only 1 remaining

### Screenshots

![Screenshot (78)](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/assets/122978299/fef9aa5a-979b-462e-addc-bdbcf411950f)

I can also fix this very easily!

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Please run the code again in your local as these errors would not come.
The error of plot_confusion_matrix is already opened before by someone. @Shiv-Expert2503

**Comment by Shiv-Expert2503** [comment]
the errors are still there @Rakesh9100 .
1st error is of path
![Screenshot (81)](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/assets/122978299/ac7bffac-6f54-46aa-bfa5-de332fe436cf)

2nd  error is of datatype error
![Screenshot (80)](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/assets/122978299/96c99d14-4cc9-455f-b22a-9b816d675d56)

**Comment by Shiv-Expert2503** [comment]
Please review them and if found valid then please assign it to me!

**Comment by Rakesh9100** [comment]
I can see 2nd one is not an error but a warning
Still assigning you @Shiv-Expert2503

**Comment by Shiv-Expert2503** [comment]
@Rakesh9100 I'm done with the code now it's working properly fine!
But I also want to implement Random Forest classifier to increase accuracy. Please allow it also!!

**Comment by Rakesh9100** [comment]
@Shiv-Expert2503 Are you working on this issue or should I close this? If yes pull the latest changes and then work on.

**Comment by Rakesh9100** [comment]
Closing this for having no response.
