### ISSUE TITLE
Develop an Interactive Drug Recommendation System

### ISSUE THREAD

**Issue by VardaPanchal005** [Rakesh9100/ML-Project-Drug-Review-Dataset#3]

**Comment by ASHWIN492** [comment]
Hey @VardaPanchal005 , I am a GSSOC contributor . I would like to work on this issue.

**Comment by ShaileeYadav** [comment]
Hey @VardaPanchal005 i am a GSSOC contributor with experience in ML and i would like to work on this issue!

**Comment by oshinsaraf** [comment]
Hey @VardaPanchal005 , could you please assign this to me, I'd love to work on this issue under GSSOC'23.

**Comment by 1912-khushi** [comment]
Hey @VardaPanchal005 , could you please assign this to me , I'd love to work on this issue and i have an intermediate experience with machine learning and did various projects based on ML

**Comment by sijalalyy** [comment]
I am GSSOC 23 contributor assign this to me i want to work on this

**Comment by Rakesh9100** [comment]
@VardaPanchal005 Assigning you, Go ahead

**Comment by mesieeeee** [comment]
hey!!
can you please assign me this issue, as i have intermediate experience working with machine learning and deep learning and i would love to work on this issue

**Comment by ayon037** [comment]
I want to contribute on this issue. Please assign me this issue under GSSOC'23.

**Comment by shubham725809** [comment]
i have already developed this type of recommendation system and I am fluent in python and its different libraries.

**Comment by chiki012** [comment]
I have experience with these types of recommendation systems. please assign me this issue.
