### ISSUE TITLE
Change the tsv files to csv

### ISSUE THREAD

**Issue by karthikbhandary2** [Rakesh9100/ML-Project-Drug-Review-Dataset#30]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

The datasets are in the tsv format. I wanted to convert it into CSV because it is the default file type we work with most of the time. Also, the main.py is showing some error that the file is not available so I wanted to see if it works this way.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by bhanuteja1901** [comment]
can you assign me this issue

**Comment by StutiShah01** [comment]
please assign this task to me as this is my first open source contribution program

**Comment by Rakesh9100** [comment]
No, code will not show error as files are present here.
CSV conversion is not needed from TSV for now. @karthikbhandary2

**Comment by karthikbhandary2** [comment]
so can you assign me to this? @Rakesh9100
