### ISSUE TITLE
Implement EDA, Data Preprocessing and Oversampling

### ISSUE THREAD

**Issue by HarshAggarwal1** [Rakesh9100/ML-Project-Drug-Review-Dataset#31]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I want to do Different EDA techniques including Statistical and Mathematical approaches and Using Traditional Models(like SVM, KNN, rtc.) and Deep Learning Models likr (CNN, RNN, etc) for checking performance and doing Data Augmentation with K fold validation to improve accuracy.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Similar issues are already open. Still assigning you @HarshAggarwal1 do try, merging will depend on the codebase and other factors

**Comment by HarshAggarwal1** [comment]
Hi, thanks for assigning this to me. Many things are not present issues before me, like, Models I am using and many EDA techniques and K fold validation also. So my issue is different from others. However, thanks again for assigning this

**Comment by Rakesh9100** [comment]
Go for it. @HarshAggarwal1
