### ISSUE TITLE
Add contributors section on README

### ISSUE THREAD

**Issue by Soumya-Kushwaha** [Rakesh9100/ML-Project-Drug-Review-Dataset#37]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Display all the contributors on readme

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by StutiShah01** [comment]
Hi @Rakesh9100, please assign this issue to me. I would like to work on it.

**Comment by Rakesh9100** [comment]
Okay @Soumya-Kushwaha Assigned

**Comment by urgetolearn** [comment]
Hello @Rakesh9100, please assign this issue to me. I would like to work on it.
