### ISSUE TITLE
Change tsv files to csv

### ISSUE THREAD

**Issue by karthikbhandary2** [Rakesh9100/ML-Project-Drug-Review-Dataset#38]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

In the datasets, we have tsv files. I would like to convert them into CSV and add them to the dataset. This would give us the option of working with either tsv or CSV

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by StutiShah01** [comment]
I would like to work on this issue

**Comment by Rakesh9100** [comment]
No, we dont require options since we have to work in the code with only one type of file. It will confuse others if both types are present. @karthikbhandary2

**Comment by karthikbhandary2** [comment]
@Rakesh9100 ok understood!

**Comment by Rakesh9100** [comment]
You can create new unique issues anytime and I will assign @karthikbhandary2
