### ISSUE TITLE
Implement EDA, preprocessing, feature engineering and model building on the dataset

### ISSUE THREAD

**Issue by Aditi-Dahiya** [Rakesh9100/ML-Project-Drug-Review-Dataset#39]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I would like to perform EDA on the given dataset along with preprocessing, feature engineering, and model building phase, and would like to increase the accuracy to >50% which is the present accuracy. I will achieve this through good data-cleaning processes. So, I would like @Rakesh9100, sir, to assign me this issue under GSSoC 2023, so that I can start working.
Thank you

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Similar issues are opened already, but still you can try and if you get more accuracy with good codebase, will merge @ADITI-2003

**Comment by karthikbhandary2** [comment]
Hey, can I use pytorch for this? @Rakesh9100 if its ok I will create a new issue

**Comment by Rakesh9100** [comment]
I think someone has opened an issue regarding pytorch, you can check, if not present then open up an issue @karthikbhandary2

**Comment by karthikbhandary2** [comment]
yeah sure

**Comment by snkt0809** [comment]
I really want to explore NLP techniques like BERT on this dataset. Kindly assign me this issue.
