### ISSUE TITLE
Implement Sentiment Analysis, EDA and Gradient Boost Algorithms

### ISSUE THREAD

**Issue by Soumya1219** [Rakesh9100/ML-Project-Drug-Review-Dataset#40]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I want to perform Sentiment Analysis and EDA like pre-processing, feature engineering and implementing N-grams and stuff like that. I think classification algorithms like XGBoost , CatBoost will increase the accuracy. 
I have good knowledge in machine learning algorithms.

Kindly assign me with this issue under GSSOC '23 :)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Assigning, proceed @Soumya1219

**Comment by BabarRasheed** [comment]
Hi, I am working on it.
