### ISSUE TITLE
Add RandomForest Model with RandomizedSearchCV

### ISSUE THREAD

**Issue by karthikbhandary2** [Rakesh9100/ML-Project-Drug-Review-Dataset#41]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I would like to enhance the project by using the RandomForest model accompanied by RandomizedSearchCV. There are other similar issues but haven't come across anywhere RandomForest was mentioned. 

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by IishuJainn** [comment]
I have used RandomForest in most of my projects so I can work with this issue.

**Comment by Rakesh9100** [comment]
@karthikbhandary2 Assigned

**Comment by tanish111** [comment]
Hi Rakesh9100 I am contributor in GSSOC and have worked with RandomForest Model in many kaggle projects and want to solve this issue if the given person is not able to solve it can you please assign it to me.
