### ISSUE TITLE
Add XGBoost, LGBM, SVR algorithms

### ISSUE THREAD

**Issue by pranavs1205** [Rakesh9100/ML-Project-Drug-Review-Dataset#45]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I would like to implement XGBoost, LGBM, SVM algorithms for above dataset.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by ayushrathore111** [comment]
I want to contribute in this issue could you please assign to me...

**Comment by Rakesh9100** [comment]
@pranavs1205 Similar issues are open, so work on this
If the codebase and accuracy will be good than others then will merge

**Comment by Rakesh9100** [comment]
@pranavs1205 Similar issues are open, still assigning you
If the codebase and accuracy will be good than others, then will merge

**Comment by Aishwarya123priya** [comment]
Can you also assign this issue to me, I want to contribute in this issue.

**Comment by ayushrathore111** [comment]
hey @Rakesh9100 I will add these algorithms to the dataset.. please assign me this asap so that I can make pull request..
