### ISSUE TITLE
Modification of word embedding technique from Tf-Idf to Word2Vec

### ISSUE THREAD

**Issue by Juhibhojani** [Rakesh9100/ML-Project-Drug-Review-Dataset#48]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I want to apply word2vec embedding technique and observe the corresponding change in accuracy. Along with it, I want to apply GridSearchCV to see if it improves accuracy of the already applied algorithm

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Assigning you @Juhibhojani
But make sure similar issues are opened before, if your codebase and accuracy comes good then will merge for sure.

**Comment by Juhibhojani** [comment]
I might need a day more to apply the word2vec embedding technique as mentioned above, I have successfully converted each sentence into a vector, but it is saved in list format in data frame, which i have to convert into different columns for giving it to ML models as input

**Comment by Rakesh9100** [comment]
Okay
