### ISSUE TITLE
Add scatter visualization of drug name and ratings

### ISSUE THREAD

**Issue by dhruvsaxena11** [Rakesh9100/ML-Project-Drug-Review-Dataset#51]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

@Rakesh9100 Dear Sir,

I am an GSSOC 2023 open source contributor and Data Science enthusiast. I will be creating multiple plot charts for data visualization and accuracy metrics visualization of the data set.

Please kindly assign me this task and It will be a great opportunity for me to work on it.

Thank you

Dhruv Saxena

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Assigning @dhruvsaxena11

**Comment by BabarRasheed** [comment]
I am a GSSOC 2023 open-source contributor and Data Science enthusiast. I am working with you. kindly assign me.
