### ISSUE TITLE
Implement data analysis and visualization and use more models

### ISSUE THREAD

**Issue by devanshidevanshidevanshi** [Rakesh9100/ML-Project-Drug-Review-Dataset#54]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Good Evening,
I am a GSSoC'23 contributor
I am willing to perform an in-depth pre-processing and EDA on the dataset, as well as adding more visualisations in order to make the analysis more easy to understand and more effective.
Furthermore, I will use more models like XGBoost, SVM, RandomForest in order to improve the accuracy.
Please assign it to me.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by ankitanain** [comment]
Hello Sir, please assign this issue to me.

**Comment by Rakesh9100** [comment]
@devanshidevanshidevanshi Assigning you
