### ISSUE TITLE
Fix error with the import of plot_confusion_matrix in collab notebook

### ISSUE THREAD

**Issue by keshavj029** [Rakesh9100/ML-Project-Drug-Review-Dataset#55]
Hello,
i would like to replace plot_confusion_matrix with ConfusionMatrixDisplay as it is supported by sklearn on every interpreter.

**Comment by karthikbhandary2** [comment]
I think someone already created an issue for this

**Comment by Rakesh9100** [comment]
Already fixed @keshavj029
