### ISSUE TITLE
Add some Issue templates

### ISSUE THREAD

**Issue by Nishitbaria** [Rakesh9100/ML-Project-Drug-Review-Dataset#57]
**Description:**

I noticed that the repository does not have an issue template. Having an issue template can greatly improve the clarity and consistency of issue reports, making it easier for contributors and maintainers to understand and address the problems or feature requests effectively.

`here are three templates that I want include:`

`Issue Template:` This template enables users to create well-structured issue reports by providing sections for a concise title, detailed description, steps to reproduce (if applicable), expected behavior, actual behavior, additional information, and environment details.
`Feature Request Template:` The feature request template allows users to outline their desired features with clarity, including sections for a clear feature description, expected benefits, and any additional context or information.
`Documentation Template: ` This template facilitates the creation of comprehensive documentation by providing a structured format, including sections for an introduction, usage instructions, examples, and other relevant details.

**Comment by Rakesh9100** [comment]
Issue template is already present and enough to open any kind of issue @Nishitbaria

**Comment by Nishitbaria** [comment]
But it is not Format So I Will make it perfect.

**Comment by Rakesh9100** [comment]
Okay assigning @Nishitbaria Will see, if it looks good then will merge

**Comment by Nishitbaria** [comment]
Thank you to assign me This issue.
