### ISSUE TITLE
Add Random Forest Classification model and other Classifier Boosting models

### ISSUE THREAD

**Issue by AkhilN7** [Rakesh9100/ML-Project-Drug-Review-Dataset#58]
@Rakesh9100  The aim is to find out the best Classification model. Please assign me this issue.

**Comment by dynamicdhxx** [comment]
@Rakesh9100 Kindly assign me this issue. I would like to try out various models on the dataset.

**Comment by Rakesh9100** [comment]
Similar issues are already opened @AkhilN7
