### ISSUE TITLE
Improve accuracy using nlp techniques

### ISSUE THREAD

**Issue by Oohatunuguntla** [Rakesh9100/ML-Project-Drug-Review-Dataset#6]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

1.We can perform preprocessing for textual data like lower casing ,removing punctuations ,stemming ,lemmatization and perform EDA
2.Use NLP techniques like N-Grams and word cloud  to get some idea about people's feedback.
3.Sentimental analysis for patient's feedback by using traditional machine learning algorithms like support vector machine, Logistic Regression in training phase and generate predictions for test data. 

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by sanikapatil06** [comment]
Can I work on this issue @Rakesh9100 ?

**Comment by Oohatunuguntla** [comment]
@sanikapatil06 
I am a GSSOC'23 contributor and i created this issue so that the owner/maintainer of this repo @Rakesh9100  can assign me this issue

**Comment by sijalalyy** [comment]
I am GSSOC 23 contributor assign this to me i want to work on this

**Comment by Rakesh9100** [comment]
@Oohatunuguntla Assigning you, Start working

**Comment by Rakesh9100** [comment]
@Oohatunuguntla Provide the update of your work pls

**Comment by Oohatunuguntla** [comment]
Yes I am working on It.I am done with point 1.I am working on generating n grams and how to choose n from that.Please give me some more time till June 4

**Comment by Rakesh9100** [comment]
@Oohatunuguntla Status pls

**Comment by Rakesh9100** [comment]
@Oohatunuguntla Status pls

**Comment by Oohatunuguntla** [comment]
Hi, requirements file is not updated to test my code end to end.I have raised issue #88 .Can you look into it and assign it to me .There is dependency here.Untill #88 is solved,I cant complete working on #6 issue.

**Comment by abhisheks008** [comment]
You can fix that requirements.txt file through this issue itself. No need to create a separate issue for that. After all you are enhancing the project.

@Rakesh9100 what do you think?

**Comment by Rakesh9100** [comment]
Yes ofc. Pls update your requirement libraries in this issue itself @Oohatunuguntla

**Comment by Rakesh9100** [comment]
Unassigning you as per your request.
