### ISSUE TITLE
Implement Patient Condition classification using Drug Reviews

### ISSUE THREAD

**Issue by nalliboinaramya** [Rakesh9100/ML-Project-Drug-Review-Dataset#61]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Hi I am contributor of GSSOC'23.I Can Improve the model by classifying the condition of patient using from the patient reviews using NLP.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Same issue is already created @nalliboinaramya

**Comment by ayesha-119** [comment]
@Rakesh9100 haven't you assigned this issue to me ?
