### ISSUE TITLE
Add Word Embedding and PCA for feature engineering

### ISSUE THREAD

**Issue by Aaditikapre** [Rakesh9100/ML-Project-Drug-Review-Dataset#63]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

i am a GSSOC'23 contributor,
Instead of using simple tf-idf vectorization with bag of words model, I wish to use word embedding models like Word2Vec, GloVe, FastText for context based vectorization of sentences instead of statistical vectorization. I also wish to reduce the dimension of feature space from 3000, to create a more condensed and easy to learn dataset using principal component analysis.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Aaditikapre** [comment]
can you please assign this issue to me sir

**Comment by aaditi-kapre** [comment]
Why is this issue not being assigned Sir?

**Comment by Rakesh9100** [comment]
Assigning @Aaditikapre
