### ISSUE TITLE
Fix minor typo in README

### ISSUE THREAD

**Issue by lem0n4id** [Rakesh9100/ML-Project-Drug-Review-Dataset#65]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Hi I am contributor of GSSOC'23. I noticed a minor typo in README file.

https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blame/main/README.md#L256 

In line 256 last word of README.md, the repo name is not correct

```diff
- Music-Recommendation-System.
+ ML-Project-Drug-Review-Dataset.
```

### Screenshots

![image](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/assets/61219881/75ba272f-520a-4c0a-8933-b6c0a1597f3a)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by lem0n4id** [comment]
I would like to make a PR for the same, if that's okay

**Comment by Rakesh9100** [comment]
Assigned @lem0n4id

**Comment by Rakesh9100** [comment]
@lem0n4id Your PR update

**Comment by lem0n4id** [comment]
> @lem0n4id Your PR update

PR is up. Apologies for the delay!
