### ISSUE TITLE
Add a plot that compares various ML model used to predict their accuracy

### ISSUE THREAD

**Issue by tanishkunigiri** [Rakesh9100/ML-Project-Drug-Review-Dataset#68]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Hello, 
I am a GSSoC'23 contributor
I am willing to create a plot that compares the various Machine learning model used in the above code to show their accuracy. This would allow the contributors to know what is the accuracy of each ML and DL algorithm used so that it is easy for them to make predictions and deploy new ML algorithms and test them or improve the statistics of the dataset and see the accuracy.
Please assign it to me.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
What plot will you create and how? Pls specify in detail @tanishkunigiri

**Comment by tanishkunigiri** [comment]
I will be creating a bar plot using the matplotlib library that can be used to visualize the accuracy of the various models at the end.

**Comment by Rakesh9100** [comment]
Plots are already created. You can check in the code as well as readme file for the plots screenshots. So what other plots will you make?

**Comment by tanishkunigiri** [comment]
Can i plot this
Confusion Matrix - Multi-Layer Perceptron Model: Plotting the confusion matrix for the multi-layer perceptron model.

**Comment by Rakesh9100** [comment]
It's already present. Do check the code in `main.py`.

**Comment by Rakesh9100** [comment]
It's already present. Do check the code in `main.py`. Pls come up with new issues.
