### ISSUE TITLE
Implement web scraping

### ISSUE THREAD

**Issue by Sushilverma002** [Rakesh9100/ML-Project-Drug-Review-Dataset#69]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Web scaping on filpkat of mobile under 50000 as it most necessary devices now days.
    1.PRODUCT NAME
     2. PRICES
     3. DESCRIPTION 
     4. REVIEW

I will do web scraping for like some pages and provide you the SOURCE code and CSV file too.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
We are working on the provided dataset only. Won't work on web scraping as for now. Try to work on other issues.

**Comment by Sushilverma002** [comment]
okay no problem
