### ISSUE TITLE
Add an interface using Html, CSS and JS for the project

### ISSUE THREAD

**Issue by Shashwat0227** [Rakesh9100/ML-Project-Drug-Review-Dataset#7]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

As it has no interface i can make one interface for the same and add some features to it 

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by shreyacupcake** [comment]
I am willing to work on this issue, please assign it to me.

**Comment by Rakesh9100** [comment]
@Shashwat0227 Assigning you, Go for it

**Comment by ghost** [comment]
sir i want to work in it. please assign me . it will be my pleasure if I work on it

**Comment by Rakesh9100** [comment]
@Shashwat0227 Update of your work pls

**Comment by Mimi97-aqua** [comment]
Hi
I would like to work on this. Please can you assign it to me?
