### ISSUE TITLE
Improve Random Forest model

### ISSUE THREAD

**Issue by sreyaad** [Rakesh9100/ML-Project-Drug-Review-Dataset#70]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I want to do OverSampling and UnderSampling on Random Forest classifier.Please assign me this issue.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Proceed @sreyaad
