### ISSUE TITLE
Implement a flask app for the model

### ISSUE THREAD

**Issue by Mridul-2003** [Rakesh9100/ML-Project-Drug-Review-Dataset#72]
### Description

Creating a flask app for your model.

**Comment by Rakesh9100** [comment]
Same issue already exist

**Comment by Mridul-2003** [comment]
So can i work on it?

**Comment by Rakesh9100** [comment]
Okay proceed, if it seems good then will merge @Mridul-2003

**Comment by Rakesh9100** [comment]
Pls wait for now. If existing ones would not be able to do, then will assign to you.
