### ISSUE TITLE
Add CodeQL workflow

### ISSUE THREAD

**Issue by metabiswadeep** [Rakesh9100/ML-Project-Drug-Review-Dataset#73]
### Description

Add the codeql semantic analysis workflow for the repo to be enabled on every push, commit and pull request.

I want to work on this issue as a part of GSSoc'23. Please assign this issue to me.

**Comment by Rakesh9100** [comment]
Can you pls provide more detail and any source or repo where this workflow is applied.

**Comment by metabiswadeep** [comment]
The dynamic cli repo of the Indian Open Source Foundation uses CodeQL. Link to the repo is attached below.
https://github.com/IndianOpenSourceFoundation/dynamic-cli

**Comment by metabiswadeep** [comment]
@Rakesh9100 Any update on this?

**Comment by Rakesh9100** [comment]
This is an innovative yet a small project. So I don't think this is required. Pls work on other issues instead of adding more workflows. @metabiswadeep
