### ISSUE TITLE
Make a ipynb file for the project

### ISSUE THREAD

**Issue by SwastikGorai** [Rakesh9100/ML-Project-Drug-Review-Dataset#75]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Running on a local system with no CUDA support might result in running on CPU which is highly inefficient. I'd like to create a .``ipynb`` notebook for the project so that users can run on Colab or other cloud platforms. @Rakesh9100 please assign this issue to me under GSSoC'23.

### Screenshots

![Screenshot (190)](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/assets/43789832/39695c1a-430d-466b-94f4-2c43dddd77ef)
 CPU and Memory both hit 100% when running on CPU with no CUDA support.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Do you want to convert `main.py` to `main.ipynb`?

**Comment by SwastikGorai** [comment]
Basically, yes. Including the other things that main.py needs like the dataset.

**Comment by Rakesh9100** [comment]
But, I am making sure that everyone is understandable of .py file but most are not familiar with jupyter notebook. So I kept .py file.

**Comment by SwastikGorai** [comment]
I will add necessary explanations whenever needed and try to make is as understandable as possible.

**Comment by Kanikawadhwa28** [comment]
I will help in optimizing as well as adding comments so that one can understand the piece of code who is novice , a complete beginner friendly code

**Comment by Rakesh9100** [comment]
@Neilblaze Pls provide your suggestion

**Comment by Kanikawadhwa28** [comment]
Actually your concern as far as I understood from the description was that
running on the cpu is highly inefficient so you can use
GPU acceleration for this purpose and further optimize the code for GPU
parallelization.

here is the implementation
import torch
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
!pip install torch torchvision

**Comment by SwastikGorai** [comment]
> Actually your concern as far as I understood from the description was that
> running on the cpu is highly inefficient so you can use
> GPU acceleration for this purpose and further optimize the code for GPU
> parallelization.
> 
> here is the implementation
> import torch
> device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
> !pip install torch torchvision
> 
> 

Yeah but it doesn't address the fundamental problem. If the device is not CUDA compatible, torch won't run on the GPU per se.  Like, for example, AMD systems

**Comment by affaannn** [comment]
> But, I am making sure that everyone is understandable of .py file but most are not familiar with jupyter notebook. So I kept .py file.

but I think code written in  .ipynb file will be more easier to understand as we can divide similar code to different cells and immediate display of outputs within the same document improves interpretability.

**Comment by affaannn** [comment]
> But, I am making sure that everyone is understandable of .py file but most are not familiar with jupyter notebook. So I kept .py file.


but I think code written in  .ipynb file will be more easier to understand as we can divide similar code to different cells and immediate display of outputs within the same document improves interpretability.

**Comment by Kanikawadhwa28** [comment]
import torch

if torch.cuda.is_available():
    device = torch.device("cuda")
    !pip install torch torchvision
else:
    device = torch.device("cpu")

Incase CUDA is not available then code sets the device to cpu and further
it can complete the execution

**Comment by Rakesh9100** [comment]
@abhisheks008 What do you think of this opened issue?

**Comment by abhisheks008** [comment]
I have gone through the whole conversation, in my perspective Jupyter Notebook file is a good approach. But there is a concern. Whenever a contributor will want to enhance the project, each and every time the .ipynb file will be removed and added iteratively. Technically the whole file will be changed for each and every contribution.

It might cause problems.
What's your thoughts on this issue?

@SwastikGorai @affaannn @Kanikawadhwa28

**Comment by Kanikawadhwa28** [comment]
In my opinion we can either use github and we can create fork to do changes
so that the history also remains saved.

**Comment by Rakesh9100** [comment]
Yes @abhisheks008 ryt. So for simplicity to newbie contributors, I prefer to keep in .py itself and not change to .ipynb for now. The one who wants can copy the code and run on their jupyter or collab notebooks. Thank you.
