### ISSUE TITLE
Implement Streamlit GUI for the Project

### ISSUE THREAD

**Issue by pooranjoyb** [Rakesh9100/ML-Project-Drug-Review-Dataset#76]
#### Why we need this improvement?
In this current version of the project, there is no GUI to provide better user interface as well as visualization.

#### How will this change help?
It will enhance the UI of the webpage. It will ensure users to dive into the pros of the model and able to explore the website about it.

#### What changes have to be introduced?
Few changes need to be done where the project has to be migrated into a module.

### How could it be implemented/designed?
The inbuilt Python package **Streamlit** will be used for GUI.

### Additional information

I shall be glad if you'd assign me this issue under GSSoC'2023. @Rakesh9100 😄

**Comment by Rakesh9100** [comment]
Okay proceed @pooranjoyb

**Comment by pooranjoyb** [comment]
Hello @Rakesh9100 I wanted to know which GUI will you be sticking to. 
I can see you've already assigned #17 for a Flask Based GUI, on the other hand I was planning to setup a simple Streamlit GUI.
So, It will be better if we stick onto one particular GUI, this is because, once it is ported to **Streamlit GUI**, it cannot be reverted to Flask based GUI and vice-versa, coz **Streamlit** is purely Python component based framework specifically built for preparing GUI for ML models. 
Please lemme know about your plans. Will be glad to contribute. Project is damn good btw! 🔥

**Comment by Rakesh9100** [comment]
You can continue working on your assigned issue with Streamlit GUI, as she is now unassigned being 2 weeks now she was assigned the issue @pooranjoyb

**Comment by pooranjoyb** [comment]
Okay, Thanks @Rakesh9100 😄

**Comment by Rakesh9100** [comment]
@pooranjoyb Update of your work pls

**Comment by pooranjoyb** [comment]
> @pooranjoyb Update of your work pls

Hello @Rakesh9100 The GUI is almost ready but I was facing issues for the integration of the `main.py` file as everything is combined in one single file. Starting from Data Analysis to Modeling. for the proper functioning of the GUI, the model has to dumped and fed with the features for the Predictions. Lemme know what should I do? Should I open a PR? (but that will be static, will not be connected to the backend)

**Comment by Rakesh9100** [comment]
No, backend should be connected ofc since static GUI interface is not a good option for proper functioning, viewing and exploring the project @pooranjoyb

**Comment by pooranjoyb** [comment]
> No, backend should be connected ofc since static GUI interface is not a good option for proper functioning, viewing and exploring the project @pooranjoyb 

Okay will be up with the PR by tonight. Thanks @Rakesh9100

**Comment by Rakesh9100** [comment]
Its been 2 weeks now so unassigning you @pooranjoyb
