### ISSUE TITLE
Add nltk library

### ISSUE THREAD

**Issue by MausmiSinha** [Rakesh9100/ML-Project-Drug-Review-Dataset#79]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

 Instead of using regular expressions for each preprocessing step, we can utilize the nltk library, which provides a variety of text preprocessing functions.

### Screenshots

![image](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/assets/105634664/d0e4660f-bc63-4d1b-bb55-6152e5cf2ee9)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Neilblaze** [comment]
@MausmiSinha Go ahead! 🚀

**Comment by Rakesh9100** [comment]
@MausmiSinha Update pls

**Comment by Rakesh9100** [comment]
Closing for having no response.
