### ISSUE TITLE
Add XGBClassifier Model and WordCloud for the Review Column

### ISSUE THREAD

**Issue by sahaycodes** [Rakesh9100/ML-Project-Drug-Review-Dataset#8]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I'm a GSSoC'23 contributor. I would like to work on this ML-project to modify its model using Text Classification techniques as well as constructing Hybrid models.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by shreyacupcake** [comment]
Prerequisites
 I am an Open Source Contributor
 I checked to make sure that this issue has not already been filed
Description
I'm a GSSoC'23 contributor. I would like to work on this issue. Please aasign it to me.

Screenshots
No response

Code of Conduct
 I follow the guidelines of this project.









Prerequisites
 I am an Open Source Contributor
 I checked to make sure that this issue has not already been filed
Description
I'm a GSSoC'23 contributor. I would like to work on this ML-project to modify its model using Text Classification techniques as well as constructing Hybrid models.

Screenshots
No response

Code of Conduct
 I follow [Contributing Guidelines](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by shreyacupcake** [comment]
Prerequisites
 I am an Open Source Contributor
 I checked to make sure that this issue has not already been filed
Description
I'm a GSSoC'23 contributor. I would like to work on this issue, please assign it to me.


Code of Conduct
 I follow Contributing Guidelines of this project.

**Comment by Sahilyadav123** [comment]
I am an Open Source Contributor
I checked to make sure that this issue has not already been filed
Description
I'm a GSSoC'23 contributor. I would like to work on this issue, please assign it to me.

Code of Conduct
I follow Contributing Guidelines of this project.

**Comment by sahaycodes** [comment]
hey guys ... I'm a GSSoC'23 contributor too ...I have raised this issue so that the owner of this repo can assign it to me

**Comment by Rakesh9100** [comment]
@sahaycodes Assigning you, Start working

**Comment by sahaycodes** [comment]
The issue should be resolved by 1st June . Will keep you posted

**Comment by Rakesh9100** [comment]
Okay @sahaycodes

**Comment by Mimi97-aqua** [comment]
Hi
I would like to work on this. Please can you assign it to me?

**Comment by sahaycodes** [comment]
@Rakesh9100 ...I have created a PR . Kindly review it.
