### ISSUE TITLE
Add Drug Review Sentiment Classification using DistilBERT Transformer Model

### ISSUE THREAD

**Issue by Mochoye** [Rakesh9100/ML-Project-Drug-Review-Dataset#80]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

The project is about building a machine-learning model to classify drug reviews as either positive or negative. Transformers are a type of neural network that are well-suited for natural language processing tasks, such as text classification.

To apply Transformers to this project, I would first need to train a transformer model on a dataset of drug reviews. The dataset should include both positive and negative reviews. Once the model is trained, I can use it to classify new drug reviews.

Once the model is trained, I can use it to classify new drug reviews. To do this, I would simply input the review text into the model and it would output a prediction of whether the review is positive or negative.

Here are some of the benefits of using Transformers for this project:

Transformers are able to learn long-range dependencies in text, which is important for tasks such as text classification.
Transformers are able to parallelize training, which can significantly reduce the amount of time it takes to train a model.
Transformers are able to generalize well to new data, which is important for tasks such as drug review classification.

Here are some of the challenges of using Transformers for this project:

Transformers can be computationally expensive to train and deploy.
Transformers require a large amount of data to train.
Transformers can be difficult to debug.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Assigned @Mochoye Start working

**Comment by Rakesh9100** [comment]
@Mochoye Status of your work

**Comment by Mochoye** [comment]
End Sems are going on so :-) will get back to work after 13th can i get an extension with the time?

**Comment by Rakesh9100** [comment]
Okay granted but make sure to not take the extension lightly, work with the time @Mochoye

**Comment by Mochoye** [comment]
Sure Thank You

**Comment by AnanyaSDhar** [comment]
I would like to work on this issue. 
I have gone through the code base.✅
I understand the issue. ✅
I have worked with transformers in NLP and Computer vision. I hope this won't be very challenging.

**Comment by AnanyaSDhar** [comment]
Thank you for assigning the issue. I'll start working on it shorty, and I will keep you updated.

**Comment by khushi-98** [comment]
Hii,
I would like to work on this project.

**Comment by AnanyaSDhar** [comment]
> Hii, I would like to work on this project.

Hi @khushi-98 , I am working on it.

**Comment by khushi-98** [comment]
Hii, That’s great. Actually I m beginner. Can u plz guide me if u would like to do. I will be glad if u help me. Sent from Mail for Windows From: Ananya SutradharSent: Saturday, June 24, 2023 11:51 PMTo: Rakesh9100/ML-Project-Drug-Review-DatasetCc: khushi-98; MentionSubject: Re: [Rakesh9100/ML-Project-Drug-Review-Dataset] Adding Transformers (Issue #80) Hii, I would like to work on this project.Hi @khushi-98 , I am working on it.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by Rakesh9100** [comment]
Update of your work pls @AnanyaSDhar

**Comment by AnanyaSDhar** [comment]
I have implemented BERT, it being a huge model crashed a few times during training so I got late. It needs some fine tuning as accuracy is not as expected.

**Comment by Rakesh9100** [comment]
Okay

**Comment by Rakesh9100** [comment]
Any Update @AnanyaSDhar

**Comment by Nabanita29** [comment]
I can work on it sir! please assign it to me!

**Comment by Rakesh9100** [comment]
@Nabanita29 Assigning you this issue, start working

**Comment by Rakesh9100** [comment]
@Nabanita29 Assigning you this issue, start working

**Comment by Rakesh9100** [comment]
Update of your work pls @Nabanita29

**Comment by Nabanita29** [comment]
I have made significant progress in implementing the model and am in the final stages of resolving the remaining errors. The work will be done very very soon sir!
