### ISSUE TITLE
Add the Arima model

### ISSUE THREAD

**Issue by ayushrathore111** [Rakesh9100/ML-Project-Drug-Review-Dataset#83]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Hii @Rakesh9100 I want to add these model in your dataset please assign this to me asap...
thank you

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by abhisheks008** [comment]
Will be good addition to this project. What do you think @Rakesh9100 ?

**Comment by Rakesh9100** [comment]
Assigning you @ayushrathore111 Proceed

**Comment by Rakesh9100** [comment]
Unassigned you for having no update @ayushrathore111

**Comment by Juhibhojani** [comment]
Hi, i would like to add LSTM to given model, not sure if i will be able to successfully apply ARIMA and SARIMA but would like to try.

**Comment by Rakesh9100** [comment]
LSTM is already added, you can check the code. I want someone to add ARIMA and SARIMA model analysis @Juhibhojani

**Comment by Juhibhojani** [comment]
I can try to add both, I need a week as exams are ongoing. I am confident that I can add these models.

**Comment by Rakesh9100** [comment]
Okay, just keep me updating @Juhibhojani

**Comment by ayushrathore111** [comment]
hii @Rakesh9100 please reassign me actually I'm out of station that's why not able to look the notifications..
assign me I'm gonna start working on it
thank you

**Comment by Rakesh9100** [comment]
Okay assigning but try to complete ASAP @ayushrathore111

**Comment by Juhibhojani** [comment]
@Rakesh9100 I think now I am not supposed to work on this right?

**Comment by Rakesh9100** [comment]
Update pls @ayushrathore111 
I will provide him just 1 more day else you will be assigned @Juhibhojani
