### ISSUE TITLE
Update Requirements

### ISSUE THREAD

**Issue by Oohatunuguntla** [Rakesh9100/ML-Project-Drug-Review-Dataset#88]
### Description

Current Forked Repository is giving me installation  errors . Libraries imblearn,keras were not present in requirements.txt. We are using this in main.py. We can update requirements.txt

**Comment by Harshu467** [comment]
I want to contribute, Can your Please assign me this task?

**Comment by Rakesh9100** [comment]
Pls update your changes in that issue only. No need for seperate one.
