### ISSUE TITLE
Add PR Template

### ISSUE THREAD

**Issue by ManasMadan** [Rakesh9100/ML-Project-Drug-Review-Dataset#90]
### Description

Pull Request Template means when someone opens a Pull Request, they will have a template that they can edit making it easier for maintainers of the project to review PR and make sure that no PR is submitted without proper description.

**Comment by ManasMadan** [comment]
@Rakesh9100 Please assign me this under GSSoC 23

**Comment by abhisheks008** [comment]
Low priority issue, but will be good addition tbh.

Thoughts @Rakesh9100 ?

**Comment by Rakesh9100** [comment]
PR template is already present. Pls work on other issues.
