### ISSUE TITLE
Add other data visualization plots

### ISSUE THREAD

**Issue by dhruvsaxena11** [Rakesh9100/ML-Project-Drug-Review-Dataset#92]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

@Rakesh9100 Respected Sir,

I want to add more visual plots for the data points of the dataset.
Please kindly assign this issue to me.

Thank you

Regards
Dhruv Saxena

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by sp9324** [comment]
Please assign this issue to me as I would like to work on it.
@Rakesh9100

**Comment by Rakesh9100** [comment]
Pls specify the name and type of plots you will add @dhruvsaxena11

**Comment by ShreeparnaDhara** [comment]
I have worked on a machine learning project in my college which you can check in this link which has data visualization tool seaborn
https://colab.research.google.com/drive/1XpY2nON3f7y2TAXyEj7FhbESdS8TdQ-2?usp=

**Comment by ShreeparnaDhara** [comment]
I would like to add barcharts ,pie charts,scatter plot

**Comment by Rakesh9100** [comment]
@ShreeparnaDhara Issues are assigned on FCFS. So pls wait.

**Comment by dhruvsaxena11** [comment]
@Rakesh9100 Respected Sir,

As I opened this issue actually wants to work on this as I wants to add more visualization charts for other features as earlier I worked on it.

So please kindly assign this issue to me


Thank you 

Dhruv Saxena

**Comment by Rakesh9100** [comment]
As you are mentioning `more` visual plots, `more` visual charts, so I want you to pls specify clearly the types of charts and plots you will add @dhruvsaxena11

**Comment by dhruvsaxena11** [comment]
Sir @Rakesh9100  I will add scatter charts and Line Charts and if required will add bar graph and histograms using matplotlib

**Comment by Rakesh9100** [comment]
Okay proceed @dhruvsaxena11

**Comment by dhruvsaxena11** [comment]
@Rakesh9100 Thank you sir. Please kindly assign the gssoc label.

**Comment by Rakesh9100** [comment]
Update pls @dhruvsaxena11

**Comment by dhruvsaxena11** [comment]
Yes Sir Sure Updating it @Rakesh9100
