### ISSUE TITLE
Optimize the hyperparameters of the existing ML models

### ISSUE THREAD

**Issue by sp9324** [Rakesh9100/ML-Project-Drug-Review-Dataset#94]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I would like to optimize the hyperparameters of the existing ML models to improve their performance by using techniques like grid search, random search, or Bayesian optimization.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Do you want to get assigned? @sp9324
