### ISSUE TITLE
Add Catboost with hyper parameter tuning

### ISSUE THREAD

**Issue by Shubhra-31** [Rakesh9100/ML-Project-Drug-Review-Dataset#95]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Implementing the CatBoost model and compare the results with other pre-exisiting models in the repo and do the hyper parameter tuning using Optuna library.

I am a GSSOC'23 contributor.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Assigning @Shubhra-31 proceed

**Comment by Rakesh9100** [comment]
Update pls @Shubhra-31

**Comment by Shubhra-31** [comment]
Will pull request by day after tomorrow, was travelling yesterday.
Thank you for your patience.
@Rakesh9100

**Comment by Shubhra-31** [comment]
I have implemented the hyper parameter tuning, it's taking decent amount of time. Will pull request as soon as the model is done running. @Rakesh9100

**Comment by Shubhra-31** [comment]
Thank you @Rakesh9100
