### ISSUE TITLE
Add Plotly analysis

### ISSUE THREAD

**Issue by ritikalath30** [Rakesh9100/ML-Project-Drug-Review-Dataset#97]
### Description

Ploty library helps in creating interactive graphs and charts which makes data easy to interpret.
I would like to implement a few charts, and bars using Plotly.

@Rakesh9100  could you assign me this part of the analysis?

**Comment by Rakesh9100** [comment]
Same issue already exist. I am keeping this on hold for now so pls wait to be assigned.

**Comment by ritikalath30** [comment]
Okay

**Comment by Rakesh9100** [comment]
Which graphs and charts will you implement? Pls tell in detail. @ritikalath30

**Comment by geyani998** [comment]
@Rakesh9100 Could you please give me chance, I will implement the following using the plotly library. 
Line Chart
Bar Chart
Pie Chart
Scatter Plot
Area Chart
Box Plot
Histogram
Heatmap
3D Scatter Plot

**Comment by geyani998** [comment]
@Rakesh9100  You can also tell me any additional ones you might want.

**Comment by Rakesh9100** [comment]
I understood but graphs, plots or charts of which model or data or which dataset you will add you need to specify as every plots has already been added. @geyani998

**Comment by Rakesh9100** [comment]
I understood but graphs, plots or charts of which model or data or which dataset you will add you need to specify as every plots has already been added @geyani998

**Comment by geyani998** [comment]
Can I do it for regression model? 
By the way, I tried downloading the dataset from the given link in the readme file, but it says not found..

**Comment by Rakesh9100** [comment]
Which regression models?

For datasets, fork and clone from this repository.

**Comment by geyani998** [comment]
@Rakesh9100, I would like to do it for Logistic and linear regression. Would do more if you like.

**Comment by Rakesh9100** [comment]
Plots are already present for these models, check the code @geyani998

**Comment by Rakesh9100** [comment]
Plots are already present for these models, pls check the code @geyani998

**Comment by geyani998** [comment]
Yes, they all have scatter plots and one boxplot, I would like to do the additional ones mentioned above, else, please tell me the kind of plots you want me to do, and I will try to do it for at least 2 models, more if time permits. (Line chart, Bar chart, Histogram, Pie chart, area chart, Histogram).

**Comment by geyani998** [comment]
@Rakesh9100

**Comment by ritikalath30** [comment]
Heyy @Rakesh9100, can I carry out this task.

**Comment by Rakesh9100** [comment]
Sure, pls provide details of the plots or graphs you will add @ritikalath30

**Comment by geyani998** [comment]
@Rakesh9100 can I proceed with the task?

**Comment by Rakesh9100** [comment]
Yes, you can proceed
You can make plots, charts, or graphs which are not present in the code for atleast 4-5 models @geyani998

**Comment by geyani998** [comment]
@Rakesh9100 Thank you, on it.

**Comment by Rakesh9100** [comment]
Update pls @geyani998

**Comment by Rakesh9100** [comment]
Update of your work pls @geyani998

**Comment by geyani998** [comment]
Yes @Rakesh9100, working on the code, will update it soon

**Comment by geyani998** [comment]
@Rakesh9100 I'm done with the code, I have implemented line chart, area chart, histogram, bar chart and pie chart for 4 algorithms, will proceed with remaining process now.

**Comment by Rakesh9100** [comment]
Okay @geyani998
