### ISSUE TITLE
Implement EDA, preprocessing, and multiple ML algorithms

### ISSUE THREAD

**Issue by devanshidevanshidevanshi** [Rakesh9100/ML-Project-Drug-Review-Dataset#99]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I am a GSSOC'23 Contributor.
The ideation is to perform pre processing on the data set, and EDA, as well as to implement a number of algorithms like XGBoost, ADAboost, SVM, LR, etc and plot a graph of the algorithm that gives the highest accuracy.
Then, plot a confusion matrix for the same. 

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
EDA and many of these algorithms are already implemented. Pls create and work on new issues.
